openapi: 3.0.0
info:
  title: Jobs_Api
  version: '1.0'
servers:
- url: https://backend-projects-fcqt.onrender.com/api/v1
paths:
  /auth/register:
    post:
      tags:
      - Auth
      summary: Register User
      operationId: RegisterUser
      requestBody:
        description: Register a new user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
            example:
              name: sagar
              email: ranasagar974@gmail.com
              password: '@ranasagar'
      responses:
        '200':
          description: User registered successfully
      security: []
  /auth/login:
    post:
      tags:
      - Auth
      summary: Login User
      operationId: LoginUser
      requestBody:
        description: Login an existing user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: ranasagar974@gmail.com
              password: anything
      responses:
        '200':
          description: User logged in successfully
      security: []
  /jobs:
    post:
      tags:
      - jobs
      summary: Create Job
      operationId: CreateJob
      requestBody:
        description: Create a new job
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJobRequest'
            example:
              company: mazadonn
              position: full stack developer
              status: pending
      responses:
        '200':
          description: Job created successfully
      security:
      - bearer: []
    get:
      tags:
      - jobs
      summary: Get All Jobs
      operationId: GetAllJobs
      responses:
        '200':
          description: A list of all jobs
      security:
      - bearer: []
  /jobs/{id}:
    delete:
      tags:
      - jobs
      summary: Delete Job
      operationId: DeleteJob
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Job deleted successfully
      security:
      - bearer: []
    put:
      tags:
      - jobs
      summary: Update Job
      operationId: UpdateJob
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Update an existing job
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJobRequest'
            example:
              company: mazadonn
              position: full stack developer
              status: pending
      responses:
        '200':
          description: Job updated successfully
      security:
      - bearer: []
    get:
      tags:
      - jobs
      summary: Get Job
      operationId: GetJob
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A single job detail
      security:
      - bearer: []
components:
  schemas:
    RegisterUserRequest:
      type: object
      required:
      - name
      - email
      - password
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    LoginUserRequest:
      type: object
      required:
      - email
      - password
      properties:
        email:
          type: string
        password:
          type: string
    CreateJobRequest:
      type: object
      required:
      - company
      - position
      - status
      properties:
        company:
          type: string
        position:
          type: string
        status:
          type: string
    UpdateJobRequest:
      type: object
      required:
      - company
      - position
      - status
      properties:
        company:
          type: string
        position:
          type: string
        status:
          type: string
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Auth
  description: Endpoints related to authentication
- name: jobs
  description: Endpoints related to job management
